Solution/BackendProj/Pages/AccountPage.cshtml.cs
using BackendProj.Models;
using BackendProj.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics.Eventing.Reader;

namespace BackendProj.Pages
{
    public class AccountPageModel : PageModel
    {
        public User user { get; set; } 
        public void OnPost(string about)
        {
            user = HttpContext.Session.Get<User>(IndexModel.userId);
            if (user.Data.About == about)
                return;
            user.Data.About = about;    
            ChangeDB.SetUser(user);
            HttpContext.Session.Remove(IndexModel.userId);
            HttpContext.Session.Set(IndexModel.userId, user);
            return;
        }

        public void OnGet(string log, string pass)
        {
            user = HttpContext.Session.Get<User>(IndexModel.userId);
        }
    }
}

Solution/BackendProj/Pages/Admin.cshtml.cs
using BackendProj.Controllers;
using BackendProj.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BackendProj.Pages
{
    public class AdminModel : PageModel
    {
        public AppDbContext db = new AppDbContext();
        public void OnGet()
        {
        }
        public IActionResult OnPostEdit(int ID)
        {
            EditorPageModel.ID = ID;
            EditorPageModel.IsEditor = true;
            return RedirectToPage("/EditorPage");
        }
        public IActionResult OnPostAdd(int ID)
        {
            EditorPageModel.ID = 0;
            EditorPageModel.IsEditor = false;
            return RedirectToPage("/EditorPage");
        }
    }
}

Solution/BackendProj/Pages/AuthError.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BackendProj.Models;
using BackendProj.Controllers;
using System.Drawing;

namespace BackendProj.Pages
{
    public class AuthErrorModel : PageModel
    {
        public IActionResult OnPost(string login, string password)
        {
            if (Authorization.GetUser(login, password) == null)
                return RedirectToPage("/AuthError");

            var user = Authorization.GetUser(login, password);
            IndexModel.userId = user.Id.ToString();

            HttpContext.Session.Set<User>(IndexModel.userId, user);
            return RedirectToPage("/AccountPage");
        }
    }
}

Solution/BackendProj/Pages/EditorPage.cshtml.cs
using BackendProj.Controllers;
using BackendProj.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Drawing;

namespace BackendProj.Pages
{
    public class EditorPageModel : PageModel
    {
        public static int ID{ get; set; }   
        public static bool IsEditor { get; set; }
        public User user { get; set; }
        public static byte[] NoImg { get; set; }
        public static byte[] UploadedImg { get; set; }
        public void OnGet()
        {
            user = Authorization.GetUser(ID);
            ImageConverter converter = new ImageConverter();
            NoImg = (byte[])converter.ConvertTo(Image.FromFile("wwwroot\\images\\Noname.JPG"), typeof(byte[]));
        }
        public IActionResult OnPostSave(string fio, string about, string login, string Password, string Role, string birthD, string educ, string doljn, string date, IFormFile photo, string achiv, string EOU, string PrevWork, string Exp)
        {
            user = Authorization.GetUser(ID);
            if (photo != null)
            {
                var stream = new MemoryStream((int)photo.Length);
                photo.CopyTo(stream);
                UploadedImg = stream.ToArray();
            }
            else {
                UploadedImg = NoImg;
            }

            if (!IsEditor)
            {
                User newUser = new User
                {
                    login = login,
                    password = Password,
                    role = int.Parse(Role),
                    Data = new Person
                    {
                        FIO = fio,
                        Doljnost = doljn,
                        DateOfEmploy = date,
                        Birthday = birthD,
                        Experience = int.Parse(Exp),
                        Education = educ,
                        Image = UploadedImg,
                        About = about, 
                        Achievments = achiv,
                        EducationOutsideUniversity = EOU,
                        PrevWorkPlace = PrevWork
                    }
                };
                newUser.Salt = Crypto.CreateSalt(5);
                newUser.password = Crypto.GenerateHash(newUser.password, newUser.Salt);
                ChangeDB.AddUser(newUser);
            }
                
            else
            {
                User newUser = user;
                newUser.login = login;
                newUser.password = user.password;
                newUser.role = int.Parse(Role);
                newUser.Data.FIO = fio;
                newUser.Data.Doljnost = doljn;
                newUser.Data.DateOfEmploy = date;
                newUser.Data.Birthday = birthD;
                newUser.Data.Experience = int.Parse(Exp);
                newUser.Data.Education = educ;
                newUser.Data.About = about;
                newUser.Data.Achievments = achiv;
                newUser.Data.EducationOutsideUniversity = EOU;
                newUser.Data.PrevWorkPlace = PrevWork;
                if (photo != null) newUser.Data.Image = UploadedImg;
                ChangeDB.SetUser(newUser);
            }
            if (ID == Convert.ToInt32(IndexModel.userId))
            {
                HttpContext.Session.Remove(IndexModel.userId);
                HttpContext.Session.Set(IndexModel.userId, user);
            }
            return RedirectToPage("/Admin");

        }
        public IActionResult OnPostDelete()
        {
            user = Authorization.GetUser(ID);
            if(IsEditor)
                Controllers.ChangeDB.DeleteUser(user);
            return RedirectToPage("/Admin");
        }
    }
}

Solution/BackendProj/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BackendProj.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Solution/BackendProj/Pages/ExtraEducationsPage.cshtml.cs
using BackendProj.Controllers;
using BackendProj.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BackendProj.Pages
{
    public class ExtraEducationsPageModel : PageModel
    {
        public User user { get; set; }
        public List<ExtraEducation> educations { get; set; }
        public List<ExtraEducation> usersEducations { get; set; }
        public void OnGet()
        {
            user = HttpContext.Session.Get<User>(IndexModel.userId);
            educations = ExtraEducationControll.GetListOfExtraEducations();
            usersEducations = ExtraEducationControll.GetExtraEducationsOfUser(user.ExtraEducationsList);
        }
        public IActionResult OnPostAdd(int educationId)
        {
            user = HttpContext.Session.Get<User>(IndexModel.userId);
            user.ExtraEducationsList.Add(educationId.ToString());
            ChangeDB.SetUser(user);
            HttpContext.Session.Remove(IndexModel.userId);
            HttpContext.Session.Set(IndexModel.userId, user);
            return RedirectToPage("/ExtraEducationsPage");
        }
        public IActionResult OnPostDelete(int educationId)
        {
            user = HttpContext.Session.Get<User>(IndexModel.userId);
            user.ExtraEducationsList.Remove(educationId.ToString());
            ChangeDB.SetUser(user);
            HttpContext.Session.Remove(IndexModel.userId);
            HttpContext.Session.Set(IndexModel.userId, user);
            return RedirectToPage("/ExtraEducationsPage");
        }
    }
}

Solution/BackendProj/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BackendProj.Models;
using BackendProj.Controllers;
using System.Drawing;

namespace BackendProj.Pages
{
    public class IndexModel : PageModel
    {
        public static string userId { get; set; } 
        public IActionResult OnPost(string login, string password)
        {
            if (Authorization.GetUser(login, password) == null)
                return RedirectToPage("/AuthError");

            var user = Authorization.GetUser(login, password);
            userId = user.Id.ToString();

            HttpContext.Session.Set<User>(userId, user);
                return RedirectToPage("/AccountPage");
        }
        public void OnGet()
        {
            if (HttpContext.Session.Keys.Contains(userId))
            {
                HttpContext.Session.Remove(userId);
            }
        }
    }
}

Solution/BackendProj/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BackendProj.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Solution/BackendProj/Pages/AccountPage.cshtml
@page

@model BackendProj.Pages.AccountPageModel
@{
    ViewData["Title"] = "Личный кабинет";
    if (Model.user.role == 0)
        Layout = "_Layout";
    else
        Layout = "_AdminLayout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device=width" />
    <link rel="stylesheet" href="~/css/Style.css" />
    <link rel="stylesheet" type="text/css" href="~/css/calendar.css" />
    <script type="text/javascript" src="~/js/calendar.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
    <style>
        body{
            font-family:Montserrat;
        }
        textarea {
            resize: none; /* Запрещаем изменять размер */
            width:400px;
            height:120px;
        }
        .classs{
            margin-left:15px
        }
    </style>
</head>

<body>
    <table>
    <tr >
        <td><p><img class="imgStyle" align="left" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.user.Data.Image))" width="200" height="250" /> </p></td>
        <td>
                <p><h1 class="classs">@Model.user.Data.FIO</h1></p>
                <p><h3 class="classs">О себе</h3></p>
                <form method="post">
                    <p class="classs" style="width:600px; height:120px">
                        <textarea rows="5" cols="50" resize"="none" name="about" id="about" style="visibility:hidden; height:0px">@Model.user.Data.About</textarea>
                        <label style="visibility:visible;" id="Label">@Model.user.Data.About</label>
                    </p>
                <p class="classs">
                        <input class="ButtonStyle" onclick="ChangeAbout()" id="Change" type="button" value="Изменить" style="visibility:visible" />
                        <input class="ButtonStyle" id="Save" type="submit" value="Сохранить" style="visibility:hidden" />
                    </p>
                </form>
        </td>
    </tr>
    <tr>
        <div id="date8" style="position: relative; right: -35%" ></div>
        <style>#cssworldru8{position: absolute}</style>
        <script>
            xCal("date8", {
            id: "cssworldru8", // Set a unique ID
            "class": "xcalend", // CSS class defines the appearance of the caledar
            hide: 0, // Do not hide the calendar
            x: 0, // Disable calendar closure button
            autoOff: 0, // Disable auto-hide
            to: "date8", // Place a calendar inside an element with an id=date8
            fn: "" // Call the function with the specified name, the selection result will be transferred to it
            });
        </script>
    </tr>
    </table>

    <button class="accordion">Личные данные</button>
    <div class="panel">
        <p> <h3>Дата рождения</h3></p>
        <ul><li>@Model.user.Data.Birthday</li></ul>
        <p> <h3>Дата приема</h3></p>
        <ul><li>@Model.user.Data.DateOfEmploy</li></ul>
        <p> <h3>Опыт</h3></p>
        <ul><li>@Model.user.Data.Experience лет - @Model.user.Data.PrevWorkPlace</li></ul>
        <p> <h3>Должность</h3></p>
        <ul><li>@Model.user.Data.Doljnost</li></ul>
    </div>

    <button class="accordion">Образование</button>
    <div class="panel">
        <p> <h3>Основное</h3></p>
        <ul><li>@Model.user.Data.Education</li></ul>
        <p><h3>Дополнительные курсы</h3></p>
        <ul><li>@Model.user.Data.EducationOutsideUniversity</li></ul>
    </div>

    <button class="accordion">Достижения</button>
    <div class="panel">
        <p><h3>Достижения</h3></p>
        <ul><li>@Model.user.Data.Achievments</li></ul>
    </div>
    

    
    

    
</body>
</html>

Solution/BackendProj/Pages/Admin.cshtml
@page
@model BackendProj.Pages.AdminModel
@{
    ViewData["Title"] = "Панель управления";
    Layout = "_Layout";
}
<html>
    <head>
    <link rel="stylesheet" href="~/css/Style.css" />
    </head>
<body>
    <div>
        <h3>Список пользователей</h3>
            <table>
                <tr align="center" style="position:relative">
                    <td><h5>ФИО работника</h5></td>
                    <td><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Роль</h5></td>
                <form method="post"><td style="position:absolute; right: -80%; top: -15%"> <input class="ButtonStyle" type="submit" asp-page-handler="Add" value="Добавить" /></td></form>
                </tr>
                @foreach (var s in Model.db.Users)
                {
                <form method="post">
                    <tr align="center" style="position:relative;">
                    <input type="hidden" name="ID" value=@s.Id />
                        <td><p>@s.Data.FIO</p></td>
                        @if (s.role == 1)
                        {
                            <td style="position:absolute; right: -13%"><p>Администратор</p></td>
                            if(s.Id.ToString()==IndexModel.userId)
                            {
                                <td style="position:absolute; right: -80%"><input class="ButtonStyle" type="submit" value="Изменить" asp-page-handler="Edit" /></td>
                            }
                        }
                        else
                        {
                            <td style="position:absolute; right: -10%"><p>Пользователь</p></td>
                            <td style="position:absolute; right: -80%"> <input class="ButtonStyle" type="submit" value="Изменить" asp-page-handler="Edit" /></td>
                        }
                    </tr>
                </form>
                }
            </table>
    </div>
</body>
</html>

Solution/BackendProj/Pages/AuthError.cshtml
@page
@model AuthErrorModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/Style.css" />
    <script src="~/js/site.js"></script>
    <style>
        body {
            font-family: Montserrat;
            background-color: #ccc;
        }
        .center {
            text-align: center;
            vertical-align: middle;
            border-radius: 10px;
            border: 5px #ccc solid;
            box-shadow: 0 0 10px #444;
            background-color: white;
            margin-top: 6%;
            width: 50%;
            margin-left: 25%;
        }
    </style>
    <title>Вход в личный кабинет</title>
</head>
<body>
    <div class ="center">
        <form method="post">
            <tr align="center">
                <br />
                <br />
                <br />
                <img src="~/images/logo.png" style="top: 50%" />
                <br />
                <br />
                <br />
            </tr>
            <tr align="center">
                <h3>Вход в личный кабинет </h3>
            </tr>
            <tr align="center">
                <label for="login">Введите логин</label>
                <br>
            </tr>
            <tr align="center">
                <input type="text" name="login" id="login" />
                <br>
                <br>
            </tr>
            <tr align="center">
                <label for="password">Введите пароль</label>
                <br>
            </tr>
            <tr align="center">
                <input type="password" name="password" id="Pass_WORD" />
            </tr>
            <tr align="center">
                <td style="position:relative">
                    <span id="pass_icon" onclick="EyeClick()"
                          style="position: absolute;top: 59%;cursor: pointer;">
                        <img src="~/images/eye.png"
                             style="width: 50px;height: 30px;">
                    </span>
                </td>
                <br>
                <br>
            </tr>
            <tr align="center">
                <input class="ButtonStyle" type="submit" value="Войти" />
            </tr>
            <br />
            <tr align="center">
                <h5 class="ErrorHeader">Неверный логин или пароль</h5>
            </tr>
        </form>
    </div>
</body>
</html>

Solution/BackendProj/Pages/EditorPage.cshtml
@page
@model BackendProj.Pages.EditorPageModel
@{
    ViewData["Title"] = "Форма записи";
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device=width" />
    <link rel="stylesheet" href="~/css/Style.css" />
    <link rel="stylesheet" type="text/css" href="~/css/calendar.css" />
    <script type="text/javascript" src="~/js/calendar.js"></script>
    <style>
        body {
            font-family: Montserrat;
        }
        .about {
            width: 400px;
            height: 120px;
        }
        .datepicker {
            position: auto;
            width: 100px;
        }
        .classs {
            margin-left: 15px
        }
    </style>
</head>

<body>
    <form method="post" enctype="multipart/form-data">
    <table>
        <tr>
            @if(EditorPageModel.IsEditor)
            {
                    <table>
                        <tr>
                            <td><p><img class="imgStyle" align="left" src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.user.Data.Image))" width="200" height="250" name="Image" /> </p></td>
                            <td>
                                <p>&nbsp;&nbsp;&nbsp;<textarea rows="1" cols="42" resize"="none" name="fio" required>@Model.user.Data.FIO</textarea></p>
                                 <p><h3 class="classs">О себе</h3></p>
                                <p class="classs"><textarea class="about" rows="5" cols="45" resize"="none" name="about" required>@Model.user.Data.About</textarea></p>
                            </td>
                        </tr>
                    </table>
                    <label class="fileUploadStyle">
                        <input type="file" name="photo" accept="image/*,image/jpeg">
                        Выбрать фото
                    </label>
                    <p> <h3>Логин</h3></p>
                    <ul><li><input name="Login" value="@Model.user.login" required></li></ul>
                    <p> <h3>Роль</h3></p>
                    <ul><li><select name="Role" required>
                        @if (@Model.user.role == 1){
                                    <option value="0">Пользователь</option>
                                    <option value="1" selected>Администратор</option> 
                        } else {
                                    <option value="0" selected>Пользователь</option>
                                    <option value="1">Администратор</option>
                        }
                    </select></li></ul>
                    <p> <h3>Дата рождения</h3></p>
                    <ul><li><input class="datepicker" name="birthD" value="@Model.user.Data.Birthday" onClick="xCal(this)" onKeyUp="xCal()" required></li></ul>
                    <p> <h3>Образование</h3></p>
                    <ul><li><textarea rows="1" cols="63" name="educ" required>@Model.user.Data.Education"</textarea></li></ul>
                    <p> <h3>Должность</h3></p>
                    <ul><li><textarea name="doljn" rows="1" cols="63" required>@Model.user.Data.Doljnost</textarea></li></ul>
                    <p> <h3>Дата приема</h3></p>
                    <ul><li><input class="datepicker" name="date" value="@Model.user.Data.DateOfEmploy" onClick="xCal(this)" onKeyUp="xCal()"required ></li></ul>
                    <p> <h3>Достижения</h3></p>
                    <ul><li><textarea rows="1" cols="63" resize"="none" name="achiv" required>@Model.user.Data.Achievments</textarea></li></ul>
                    <p> <h3>Дополнительные курсы</h3></p>
                    <ul><li><textarea rows="1" cols="63" resize"="none" name="EOU" required>@Model.user.Data.EducationOutsideUniversity</textarea></li></ul>
                    <p> <h3>Предыдущее место работы</h3></p>
                    <ul><li><textarea rows="1" cols="63" resize"="none" name="PrevWork" required>@Model.user.Data.PrevWorkPlace</textarea></li></ul>
                    <ul><li><input style="width: 30px" name="Exp" value="@Model.user.Data.Experience" required>&nbsp;&nbsp;лет</li></ul>
            }
                else if(!EditorPageModel.IsEditor)
            {
                    <table>
                        <tr>
                            <td><p><img class="imgStyle" align="left" src="data:image/jpeg;base64,@(Convert.ToBase64String(EditorPageModel.NoImg))" width="200" height="250" name="Image" /> </p></td>
                            <td>
                                <p>&nbsp;&nbsp;&nbsp;<textarea rows="1" cols="42" resize"="none" name="fio"></textarea></p>
                                <p><h3 class="classs">О себе</h3></p>
                                <p class="classs"><textarea class="about" rows="5" cols="45" resize"="none" name="about"></textarea></p>
                            </td>
                        </tr>
                    </table>
                    <label class="fileUploadStyle">
                        <input type="file" name="photo" accept="image/*,image/jpeg">
                        Выбрать фото
                    </label>
                    <p> <h3>Логин</h3></p>
                    <ul><li><input name="Login" required></li></ul>
                    <p> <h3>Роль</h3></p>
                    <ul><li><select name="Role" required>
                        <option value="0">Пользователь</option>
                        <option value="1">Администратор</option>
                    </select></li></ul>
                    <p> <h3>Дата рождения</h3></p>
                    <ul><li><input class="datepicker" name="birthD" onClick="xCal(this)" onKeyUp="xCal()" required></li></ul>
                    <p> <h3>Образование</h3></p>
                    <ul><li><textarea name="educ" rows="1" cols="63" required></textarea></li></ul>
                    <p> <h3>Должность</h3></p>
                    <ul><li><textarea rows="1" cols="63" name="doljn" required></textarea></li></ul>
                    <p> <h3>Дата приема</h3></p>
                    <ul><li><input class="datepicker" name="date" onClick="xCal(this)" onKeyUp="xCal()" required></li></ul>
                    <p> <h3>Достижения</h3></p>
                    <ul><li><textarea rows="1" cols="63" resize"="none" name="achiv" required></textarea></li></ul>
                    <p> <h3>Дополнительные курсы</h3></p>
                    <ul><li><textarea rows="1" cols="63" resize"="none" name="EOU" required></textarea></li></ul>
                    <p> <h3>Предыдущее место работы</h3></p>
                    <ul><li><textarea rows="1" cols="63" resize"="none" name="PrevWork" required></textarea></li></ul>
                    <ul><li><input style="width: 30px" name="Exp" required>&nbsp;&nbsp;лет</li></ul>
            }
        <td><input class="ButtonStyle" type="submit" asp-page-handler="Save" value="Сохранить" name="save" /></td>
        <td>
            @if(EditorPageModel.IsEditor)
            {
                        <input class="ButtonStyle" type="submit" value="Удалить" asp-page-handler="Delete" name="delete" />
            }
            else
            {
                        <input class="ButtonStyle" type="submit" value="Отмена" asp-page-handler="Delete" name="delete" />
            }
        </td>
    </form>
</body>
</html>

Solution/BackendProj/Pages/ExtraEducationsPage.cshtml
@page
@model BackendProj.Pages.ExtraEducationsPageModel
@{
    ViewData["Title"] = "Дополнительные курсы";
    if (Model.user.role == 1)
    {
        Layout = "_AdminLayout";
    }
    else
    {
        Layout = "_Layout";
    }
}

<!DOCTYPE html>

<html>
<head>
        <meta name="viewport" content="width=device=width" />
        <link rel="stylesheet" href="~/css/Style.css"/>
        <link rel="stylesheet" href="~/Layout.cshtml.css"/>
</head>
<body>
    <form method="post">
    <table>
    <tr style="position:relative">
    <td style="position: absolute; margin-left: 80px; overflow: auto">
    <h5>Все курсы</h5>
    @foreach(var dbElem in Model.educations)
    {
        <ul>
        <li class="liStyle"><h5 class="listHeader">@dbElem.Theme</h5>
        <h6 class="listBody">@dbElem.Description</h6>
        <h6 class="listBody">@dbElem.Duration</h6>
        @if(!Model.user.ExtraEducationsList.Contains(dbElem.Id.ToString())){
           <label class="ButtonStyle">
                <input value="@dbElem.Id" asp-page-handler="Add" type="submit" name="educationId">
                Записаться
           </label>
        }
        </li>
        </ul>
    }
    </td>
    <td style="position:absolute; margin-left: 800px; overflow: auto">
    <h5>Мои курсы</h5>
    @foreach(var userElem in Model.usersEducations)
    {
        <ul>
        <li class="liStyle"><h5 class="listHeader">@userElem.Theme</h5>
        <h6 class="listBody">@userElem.Description</h6>
        <h6 class="listBody">@userElem.Duration</h6>
        <label class="ButtonStyle">
            <input value="@userElem.Id" asp-page-handler="Delete" type="submit" name="educationId">
            Отписаться
        </label>
        </li>
        </ul>
    }
    </td>
    </tr>
    </table>
    </form>
</body>
</html>

Solution/BackendProj/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Вход";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/Style.css" />
    <link rel="shortcut icon" href="~/irz.ico" />
    <script src="~/js/site.js"></script>
    <style>
        body {
            font-family: Montserrat;
            background-color: #ccc;
        }
        .center {
            text-align: center;
            vertical-align: middle;
            border-radius: 10px;
            border: 5px #ccc solid;
            box-shadow: 0 0 10px #444;
            background-color: white;
            margin-top: 6%;
            width: 50%;
            margin-left: 25%;
        }
    </style>
    <title>Вход в личный кабинет</title>
</head>
<body onload="BodyLoad()">
    <div class ="center">
       <form method="post">
            <tr align="center">
                <br />
                <br />
                <br />
                <img src="~/images/logo.png" style="top: 50%" />
                <br />
                <br />
                <br />
            </tr>
            <tr align="center">
                <h3>Вход в личный кабинет </h3>
            </tr>
            <tr align ="center">
                 <label for="login" >Введите логин</label><br>
            </tr>
            <tr align="center">
                <input type="text" name="login" id="login" /><br><br>
            </tr>
            <tr align="center">
                <label for="password">Введите пароль</label><br>
            </tr>
            <tr align="center">
                <input type="password" name="password" id="Pass_WORD" />
            </tr>
            <tr align="center">
                <td style="position:relative">
                    <span id="pass_icon" onclick="EyeClick()"
                        style="position: absolute;top: 59%;cursor: pointer;">
                        <img src="~/images/eye.png"
                          style="width: 50px;height: 30px;">
                    </span>
                </td>
                <br>
                <br>
            </tr>
            <tr align="center">
                <input class="ButtonStyle" type="submit" value="Войти" />
            </tr>
            <br />
            <br />
            <br />
            <br />
        </form>
    </div>
</body>
</html>